import { ApiNewsCategory, ApiNewsCountry } from "ts-newsapi/lib/types";

export const mustIncludeAtLeastOneTopHeadlines =
  "Must include at least one of the options";
export const mustIncludeAtLeastOneEverything =
  "Must include at least one of the following options- q, source, or domain";
export const API = "API";
export const Must = "Must";
export const tooManyRequests = "Too many requests";
export const unknownError = "Unknown error";
export const exceededFreeTierLimit = "Excceded free tier limit of 100 results";
export const internalServerErrors = "Internal server errors";

export const tagsKeywords = {
  Money: [
    "crypto",
    "budget",
    "money",
    "$",
    "stock",
    "bitcoin",
    "salary",
    "bank",
    "sell",
    "buy",
    "dollar",
    "transaction",
    "כסף",
    "שקל",
    "מניה",
    "מניות",
    "שכר",
  ],
  Crime: [
    "gun",
    "kill",
    "blood",
    "police",
    "thie",
    "crime",
    "arrest",
    "weapon",
    "attack",
    "threat",
    "אלימות",
    "דם",
    "הרג",
    "נשק",
  ],
  Tech: [
    "tech",
    "crypto",
    "stream",
    "digital",
    "electric",
    "tv",
    "app",
    "device",
    "data",
    "phone",
    "computer",
    "gaming",
    "gamer",
    "טכנולוגיה",
    "טלפון",
    "גיימ",
    "מחשב",
  ],
  Politics: [
    "election",
    "senat",
    "china",
    "minister",
    "mayor",
    "elector",
    "republic",
    "vote",
    "senate",
    "government",
    "democ",
    "president",
    "politic",
    "מנדט",
    "פוליטיק",
    "ממשלה",
    "בחירות",
  ],
  Sport: [
    "ufc",
    "football",
    "soccer",
    "nba",
    "athlete",
    "sport",
    "gym",
    "medal",
    "ספורט",
    "מדליה",
    "אליפות",
  ],
  Health: [
    "health",
    "therap",
    "vaccin",
    "nurse",
    "hospital",
    "medical",
    "medicine",
    "corona",
    "cure",
    "doctor",
    "בריאות",
    "רופא",
    "תרופה",
    "חיסון",
  ],
  Disaster: [
    "fire",
    "tsunami",
    "hurricane",
    "earthquake",
    "volcan",
    "storm",
    "disaster",
    "שריפה",
    "רעידת",
    "אסון",
  ],
  Showbiz: [
    "gossip",
    "celeb",
    "paparazzi",
    "movie",
    "artist",
    "music",
    "premiere",
    "reality",
    "הקרנה",
    "כוכב",
    "מפורסם",
    "סלב",
    "רכילות",
    "בידור",
  ],
};
export const moneyTag = "Money";
export const crimeTag = "Crime";
export const techTag = "Tech";
export const politicsTag = "Politics";
export const sportTag = "Sport";
export const healthTag = "Health";
export const disasterTag = "Disaster";
export const showbizTag = "Showbiz";

export const badData = "Invalid Data Received";

export const countries: ApiNewsCountry[] = [
  "ae",
  "ar",
  "at",
  "au",
  "be",
  "bg",
  "br",
  "ca",
  "ch",
  "cn",
  "co",
  "cu",
  "cz",
  "de",
  "eg",
  "fr",
  "gb",
  "gr",
  "hk",
  "hu",
  "id",
  "ie",
  "il",
  "in",
  "it",
  "jp",
  "kr",
  "lt",
  "lv",
  "ma",
  "mx",
  "my",
  "ng",
  "nl",
  "no",
  "nz",
  "ph",
  "pl",
  "pt",
  "ro",
  "rs",
  "ru",
  "sa",
  "se",
  "sg",
  "si",
  "sk",
  "th",
  "tr",
  "tw",
  "ua",
  "us",
  "ve",
  "za",
];
export const categories: ApiNewsCategory[] = [
  "business",
  "entertainment",
  "general",
  "health",
  "science",
  "sports",
  "technology",
];
