export const apiStrings: { [key: string]: string[] } = {
  TopHeadlinesOptions: ["Country", "Catagory", "Sources"],
  Country: [
    "ae",
    "ar",
    "at",
    "au",
    "be",
    "bg",
    "br",
    "ca",
    "ch",
    "cn",
    "co",
    "cu",
    "cz",
    "de",
    "eg",
    "fr",
    "gb",
    "gr",
    "hk",
    "hu",
    "id",
    "ie",
    "il",
    "in",
    "it",
    "jp",
    "kr",
    "lt",
    "lv",
    "ma",
    "mx",
    "my",
    "ng",
    "nl",
    "no",
    "nz",
    "ph",
    "pl",
    "pt",
    "ro",
    "rs",
    "ru",
    "sa",
    "se",
    "sg",
    "si",
    "sk",
    "th",
    "tr",
    "tw",
    "ua",
    "us",
    "ve",
    "za",
  ],
  Catagory: [
    "business",
    "entertainment",
    "general",
    "health",
    "science",
    "sports",
    "technology",
  ],
  EverythingOptions: ["Sort by", "Dates", "Sources", "Language"],
  Language: [
    "ar",
    "de",
    "en",
    "es",
    "fr",
    "he",
    "it",
    "nl",
    "no",
    "pt",
    "ru",
    "se",
    "ud",
    "zh",
  ],
  ["Sort by"]: ["relevancy", "popularity", "publishedAt"],
};
export const cardString = {
  NavigateToDispatch: "NAVIGATE TO DISPATCH",
  Continue: "CONTINUE",
};
export const graphString = {
  noDataToDisplay: "No data to display",
  containerClass: "flex column graph",
  cardLayoutClass: "graph",
};
export const headerStrings = {
  SignOut: "Sign Out",
  UserInitials: "ON",
  Search: "Search",
};
export const loginString = {
  title: "Welcome to Dispatcher",
  desc: "Locate articles and breaking news headlines from news sources and blogs across the web",
};
export const searchBarStrings = {
  searchDropDownOptions: ["Top Headlines", "Everything"],
  noMatches: "We couldn't find any matches for your query",
  noMatchesContainerClasses: "flex column",
};
export const storyStrings = {
  HeaderTitle: "HEADER",
  UITitle: "UI",
  CardTitle: "CARD",
  DashTitle: "DASHBOARD",
  LoginTitle: "Login",
};
